---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: __app__
  namespace: __namespace__
  labels:
    app: __app__
    environment: __env__
    namespace: __namespace__
    project: __project__
    version: v1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-__namespace__-__app__
  template:
    metadata:
      labels:
        app: __app__
        environment: __env__
        namespace: __namespace__
        project: __project__
        version: v1
        workload.user.cattle.io/workloadselector: apps.deployment-__namespace__-__app__
    spec:
      containers:
        - env:
            - name: NEXT_PUBLIC_BASE_DOMAIN
              value: __NEXT_PUBLIC_BASE_DOMAIN__
            - name: NEXT_PUBLIC_API_URI
              value: __NEXT_PUBLIC_API_URI__
          image: __image__
          imagePullPolicy: Always
          name: frontend
          ports:
            - containerPort: 3000
              name: 3000tcp
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 512Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: __app__
  namespace: __namespace__
  labels:
    app: __app__
    service: __app__
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: __app__
    namespace: __namespace__
  sessionAffinity: None
  type: ClusterIP
