---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-next
  namespace: kiwisheets-__env__
  labels:
    app: frontend-next
    environment: __env__
    namespace: kiwisheets-__env__
    project: kiwisheets
    version: v1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-test-default-pgadmin
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      app: frontend-next
      environment: __env__
      namespace: kiwisheets-__env__
      project: kiwisheets
      version: v1
    spec:
      containers:
        - env:
            - name: NEXT_PUBLIC_BASE_DOMAIN
              value: __NEXT_PUBLIC_BASE_DOMAIN__
            - name: NEXT_PUBLIC_API_URI
              value: __NEXT_PUBLIC_API_URI__
          image: __image__
          imagePullPolicy: Always
          name: frontend
          ports:
            - containerPort: 3000
              name: 3000tcp
              protocol: TCP
          resources:
            limits:
              cpu: "100"
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-next
  namespace: kiwisheets-__env__
  labels:
    app: frontend-next
    service: frontend-next
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: frontend-next
    namespace: kiwisheets-__env__
  sessionAffinity: None
  type: ClusterIP
