apiVersion: apps/v1
kind: Deployment
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-test-default-pgadmin
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    spec:
      containers:
        - env:
            - name: NEXT_PUBLIC_BASE_DOMAIN
              value: __NEXT_PUBLIC_BASE_DOMAIN__
            - name: NEXT_PUBLIC_API_URI
              value: __NEXT_PUBLIC_API_URI__
          image: __image__
          imagePullPolicy: Always
          name: frontend
          ports:
            - containerPort: 3000
              name: 3000tcp
              protocol: TCP
          resources:
            limits:
              cpu: "100"
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
